# Basic set up for three package managers

version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/NodejsWebApp1"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/WebApplication1"
    schedule:
      interval: "daily"
